import type { Metadata } from "next";
import { Geist, Carrois_Gothic_SC } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/shared/Sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const carrois = Carrois_Gothic_SC({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-one",
});

export const metadata: Metadata = {
  title: "Restaurant Front Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${carrois.variable} antialiased`}>
        <Toaster />
        {/* <div className="fixed top-0 left-0 w-full z-50">
          <Header />
        </div> */}
        {children}
      </body>
    </html>
  );
}
